stages:
  fit-model:
    cmd: Rscript model.R
    deps:
    - model.R
    - data/tweets.csv
    - data/products.csv
    outs:
    - tune.png
    - final.png
    - fold.png
    - fit.md
    - preprocessor_summary.md
    - session.md
    params:
    - tune.penalty_min
    - tune.penalty_max
    - tune.penalty_levels
    - tune.tokens_max
    metrics:
    - metrics.json:
        cache: false
