stages:
  fit-model:
    cmd: Rscript model.R
    deps:
    - model.R
    - data/tweets.csv
    - data/products.csv
    outs:
    - fit.md
    - conf.png
    params:
    - tune.penalty
    metrics:
    - metrics.json:
        cache: false
