name: cml
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: r-lib/actions/setup-r@master
      - name: ML Pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sh dependencies.sh
          dvc pull
          dvc repro
          git fetch --prune

          echo "## Diff" >> report.md
          dvc params diff main --show-md >> report.md
          dvc metrics diff main --show-md >> report.md

          echo "## Variables" >> report.md
          cat preprocessing_summary.md >> report.md

          echo "## Final fit" >> report.md
          cml-publish final.png >> report.md

          echo "## Fold fits" >> report.md
          cml-publish fold.png >> report.md

          echo "## Fit information" >> report.md
          cat fit.md >> report.md

          echo "## Tuning information" >> report.md
          cat tune.md >> report.md

          echo "## Session information" >> report.md
          cat session.md >> report.md

          cml-send-comment report.md
      - name: Commit Results
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Tyler Littlefield
          author_email: tylerlittlefield@hey.com
          message: "ML Pipeline Results"
          add: "metrics.json estimates.csv"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
