name: cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: r-lib/actions/setup-r@master
      - name: ML Pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc pull
          dvc repro
          cat outputs/fit.md >> report.md
          cat outputs/conf.md >> report.md
          cat outputs/accuracy.md >> report.md
          cml-send-comment report.md
